language: node_js
node_js:
  - "10.16.0"
# Speeds up build time since it doesn't have to install the same packages again.
cache:
  directories:
    - node_modules

install:
  # Locking CodeCov verion due to Travis issues https://github.com/codecov/codecov-node/issues/184
  - npm install -g codecov
  - npm install

script:
  - npm run test && codecov
