version: "3.4"

services:
  "password-manager":
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: password-manager
    image: theonewhoknocks/password-manager
    environment:
      NODE_ENV: production
      NODE_EXTRA_CA_CERTS: /home/node/app/certs/localhost.crt
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/certs.localhost:/home/node/app/certs"
      - "${PWD}/data:/home/node/app/data"
