services:
  password-manager:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: password-manager
    image: theonewhoknocks/password-manager
    environment:
      DATA_PATH: /home/node/app/data
      NODE_ENV: production
      NODE_EXTRA_CA_CERTS: /home/node/app/certs/localhost.crt
      TZ: America/Los_Angeles
    ports:
      - "3000:3000"
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      - type: bind
        source: "${PWD}/certs"
        target: "/home/node/app/certs"
      - type: bind
        source: "${PWD}/e2e/mnt/data"
        target: "/home/node/app/data"
  
  password_manager_dev:
    extends: password-manager # allows for just changing key pieces of data for development
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: password_manager_dev
    environment:
      NODE_ENV: development
    ports:
      # browserSync
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      # inspector
      - "9229:9229"
    volumes:
      # Map shell files over, so they're maintained between sessions
      - "${PWD}/.docker/.vimrc:/home/node/.vimrc"
      - "${PWD}/.docker/.zshrc:/home/node/.zshrc"
      - "${PWD}/.ignore:/home/node/dev" # allows for .zsh_history to be written
      # Map the current directory over for development
      - "${PWD}:/home/node/app"
  
  e2e-passman:
    container_name: e2e-passman
    depends_on:
      - password-manager
    environment:
      ## Cypress vars
      CYPRESS_BASE_URL: "${CYPRESS_BASE_URL}"
      # DEBUG: cypress:server:browsers:electron # view Electron internal logging
      # ELECTRON_ENABLE_LOGGING: 1 # view console logs from Browser (headless)
    hostname: cypresstests
    image: cypress/included:9.3.0
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ports:
      - "9001:3000"
    privileged: true
    user: "${CURR_UID}:${CURR_GID}"
    working_dir: /repo/e2e
    volumes:
      - "${PWD}/e2e:/repo/e2e"
      - type: bind
        source: "${PWD}/e2e/mnt/data"
        target: "/repo/e2e/cypress/fixtures"
